Repository double-slash-podcast/website, pull requests merged in 2022-11, with the labels that each got.

#54 Add Lazy and fix text size and spacing
  components/AnimateBackground.vue
  components/EpisodeHeadings.vue
  components/Footer.vue
  components/Header.vue
  pages/index.vue
  pages/podcasts/[slug].vue
Labels: enhancement

#56 Fix SVG slashes home scroll effect, fix error 'pause' and move SVG to bottom for CLS
  components/Footer.vue
  components/global/SlashIcon.vue
  pages/index.vue
Labels: bug

#53 Add 51 episode note
  components/EpisodeHeadings.vue
  components/PlayerRemote.vue
  content/podcasts/051.docusaurus/index.md
  pages/podcasts/[slug].vue
Labels: episode

#58 improve speed !
  cache/db/storage.json
  cache/index.ts
  components/AnimateBackground.vue
  components/Cohost.vue
  components/PodcastList.vue
  layouts/default.vue
  package.json
  pages/index.vue
  pages/podcasts/[slug].vue
  pnpm-lock.yaml
  server/routes/podcast-rss-feed.xml.ts
Labels: enhancement

#64 create function for predict height of header.
  components/Header.vue
Labels: bug, enhancement

#68 update Nuxt to RC 13
  components/global/AppleIcon.vue
  nuxt.config.ts
  package.json
  pnpm-lock.yaml
Labels: chore

#69 set font inter variable
  assets/fonts/Inter-VariableFont.woff2
  assets/main.css
  layouts/default.vue
Labels: bug

#70 Fix text
  assets/main.css
  components/content/ProseA.vue
  components/content/ProseH2.vue
  components/global/Authors.vue
  content/podcasts/001.prologue/index.md
  content/podcasts/002.jamstack/index.md
  content/podcasts/003.ecoconception/index.md
  content/podcasts/004.ecommerce-statique/index.md
  content/podcasts/005.github-ninja/index.md
  content/podcasts/006.jamstack-conf/index.md
  content/podcasts/007.tailwindcss/index.md
  content/podcasts/008.seo/index.md
  content/podcasts/009.jquery/index.md
  content/podcasts/010.pair-coding/index.md
  content/podcasts/011.progressive-web-app/index.md
  content/podcasts/012.github-readme/index.md
  content/podcasts/013.graphql-hype-or-revolution/index.md
  content/podcasts/014.e-commerce-state-2020/index.md
  content/podcasts/015.news-octobre-2020/index.md
  content/podcasts/016.azure-static-web-app/index.md
  content/podcasts/017.e-commerce-snipcart/index.md
  content/podcasts/018.javascript-alpine-js/index.md
  content/podcasts/019.jamstatic-fr-forestry/index.md
  content/podcasts/020.fastify-node-js-open-source/index.md
  content/podcasts/021.strapi/index.md
  content/podcasts/022.vite-bundler/index.md
  content/podcasts/023.meilisearch/index.md
  content/podcasts/024.core-web-vitals/index.md
  content/podcasts/025.site-statique-10000-pages/index.md
  content/podcasts/026.wasm/index.md
  content/podcasts/027.back-to-school/index.md
  content/podcasts/028.prisma-orm/index.md
  content/podcasts/029.nuxt-sebastien-chopin/index.md
  content/podcasts/030.bit-dev-olivier-combe/index.md
  content/podcasts/031.redwood-js/index.md
  content/podcasts/032.hasura/index.md
  content/podcasts/033.web3/index.md
  content/podcasts/034.news-avril-2022/index.md
  content/podcasts/035.state-of-front-2022/index.md
  content/podcasts/036.analytics22/index.md
  content/podcasts/037.state-of-hosting-2022/index.md
  content/podcasts/038.typescript/index.md
  content/podcasts/039.news-juin-2022/index.md
  content/podcasts/040.web-platform-2022/index.md
  content/podcasts/041.edge-computing/index.md
  content/podcasts/042.lottie-svg-animation/index.md
  content/podcasts/043.three-js/index.md
  content/podcasts/044.animeCSS/index.md
  content/podcasts/047.pwa_builder/index.md
  content/podcasts/048.seo-2022/index.md
  content/podcasts/049.news-octobre-22/index.md
  content/podcasts/050.episode-50/index.md
  content/podcasts/051.docusaurus/index.md
  nuxt.config.ts
  pages/index.vue
  pages/podcasts/[slug].vue
  server/routes/podcast-rss-feed.xml.ts
  tailwind.config.js
Labels: bug, enhancement

#73 fix long link in episode note. Set all episodes link under list home.
  assets/main.css
  components/EpisodeHeadings.vue
  pages/index.vue
  pages/podcasts/index.vue
Labels: bug, enhancement

#76 update tab with custom system instead headlessui
  pages/index.vue
  pages/podcasts/[slug].vue
Labels: enhancement

#75 add episode 52
  cache/db/storage.json
  content/podcasts/052.news-novembre-2022/index.md
Labels: episode

#67 schema org
  composables/useHeadPodcast.ts
  config.ts
  declaration.d.ts
  layouts/default.vue
  nuxt.config.ts
  package.json
  pages/index.vue
  pages/podcasts/[slug].vue
  pages/podcasts/index.vue
  pnpm-lock.yaml
  public/logo.png
Labels: enhancement

#78 Fix/multiple stuff
  components/global/NotFoundIcon.vue
  composables/useHeadPodcast.ts
  content/podcasts/015.news-octobre-2020/index.md
  content/podcasts/020.fastify-node-js-open-source/index.md
  content/podcasts/021.strapi/index.md
  pages/[...slug].vue
  pages/podcasts/[slug].vue
  pages/podcasts/index.vue
Labels: enhancement

#80 add content pages
  components/Navbar.vue
  content/custom/nous-soutenir.md
  pages/[...slug].vue
  pages/_404.vue
  pages/podcasts/[slug].vue
  server/routes/sitemaps.xml.ts
Labels: enhancement, structure

#81 add episode RoR
  content/podcasts/053.ruby-on-rails/index.md
Labels: episode

#82 api sponsor for show avatar
  cache/db/storage.json
  components/Navbar.vue
  components/global/Sponsor.vue
  content/custom/nous-soutenir.md
  content/podcasts/001.prologue/index.md
  content/podcasts/002.jamstack/index.md
  content/podcasts/003.ecoconception/index.md
  content/podcasts/004.ecommerce-statique/index.md
  content/podcasts/005.github-ninja/index.md
  content/podcasts/006.jamstack-conf/index.md
  content/podcasts/007.tailwindcss/index.md
  content/podcasts/008.seo/index.md
  content/podcasts/009.jquery/index.md
  content/podcasts/010.pair-coding/index.md
  content/podcasts/011.progressive-web-app/index.md
  content/podcasts/012.github-readme/index.md
  content/podcasts/013.graphql-hype-or-revolution/index.md
  content/podcasts/014.e-commerce-state-2020/index.md
  content/podcasts/015.news-octobre-2020/index.md
  content/podcasts/016.azure-static-web-app/index.md
  content/podcasts/017.e-commerce-snipcart/index.md
  content/podcasts/018.javascript-alpine-js/index.md
  content/podcasts/019.jamstatic-fr-forestry/index.md
  content/podcasts/020.fastify-node-js-open-source/index.md
  content/podcasts/021.strapi/index.md
  content/podcasts/022.vite-bundler/index.md
  content/podcasts/023.meilisearch/index.md
  content/podcasts/024.core-web-vitals/index.md
  content/podcasts/025.site-statique-10000-pages/index.md
  content/podcasts/026.wasm/index.md
  content/podcasts/027.back-to-school/index.md
  content/podcasts/028.prisma-orm/index.md
  content/podcasts/029.nuxt-sebastien-chopin/index.md
  content/podcasts/030.bit-dev-olivier-combe/index.md
  content/podcasts/031.redwood-js/index.md
  content/podcasts/032.hasura/index.md
  content/podcasts/033.web3/index.md
  content/podcasts/034.news-avril-2022/index.md
  content/podcasts/035.state-of-front-2022/index.md
  content/podcasts/038.typescript/index.md
  content/podcasts/039.news-juin-2022/index.md
  content/podcasts/040.web-platform-2022/index.md
  content/podcasts/041.edge-computing/index.md
  content/podcasts/042.lottie-svg-animation/index.md
  content/podcasts/043.three-js/index.md
  content/podcasts/044.animeCSS/index.md
  content/podcasts/047.pwa_builder/index.md
  content/podcasts/048.seo-2022/index.md
  content/podcasts/049.news-octobre-22/index.md
  content/podcasts/050.episode-50/index.md
  content/podcasts/051.docusaurus/index.md
  content/podcasts/052.news-novembre-2022/index.md
  content/podcasts/053.ruby-on-rails/index.md
  nuxt.config.ts
  pages/[...slug].vue
  pages/podcasts/[slug].vue
  pages/podcasts/index.vue
  server/routes/github-sponsor.json.ts
Labels: enhancement, Add feature
